# Numpy 

In [2]:
import numpy as np

In [12]:
a = np.array(())
b = np.array([])
print(a)

[]


In [13]:
a

array([], dtype=float64)

In [14]:
b

array([], dtype=float64)

In [16]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [20]:
a = np.array([[1,2,3], [4,5,6]])
print(a)
# element of the row and column should be same

[[1 2 3]
 [4 5 6]]


In [22]:
a.size # How many elements in th matrix

6

In [23]:
a.dtype # type of data types

dtype('int32')

In [24]:
a.ndim # number of dimensions 

2

In [25]:
a.itemsize # how many bytes are alocated to each element

4

In [26]:
a.shape # number of rows and column

(2, 3)